"""
=============================================================================
TV Streaming Services — NLP Sentiment Analysis Engine
Netflix · Disney+ · HBO Max · Amazon Prime · Apple TV+ · Peacock
2020 – 2026
=============================================================================
⚠️  ACADEMIC RESEARCH DISCLAIMER

1. EDUCATIONAL PURPOSE ONLY
   This repository, including all source code, NLP models, sentiment
   indicators, and visualizations, is developed strictly for educational,
   academic research, and portfolio demonstration purposes.

2. NOT FINANCIAL ADVICE
   No content or output generated by this pipeline constitutes professional
   financial, investment, legal, or tax advice. Sentiment scores derived
   from simulated news data do not guarantee future stock performance.

3. NO LIABILITY FOR LOSS
   The author is not liable for any commercial losses or investment
   decisions made based on this codebase or documentation.

4. DATA LIMITATIONS
   Sentiment data is synthetically generated using real-world event
   timelines (platform launches, earnings reports, subscriber milestones)
   calibrated against published industry data. Headlines are simulated
   to model realistic NLP pipeline behavior.

METHODOLOGY OVERVIEW:
   Step 1 — Data Acquisition: Daily headline counts and sentiment proxies
             per streaming platform (Netflix, Disney+, HBO Max, etc.)
   Step 2 — Text Preprocessing: Tokenization, cleaning, 512-token BERT limit
   Step 3 — Sentiment Quantification: FinBERT-style positive/negative/neutral
             classification → Net Sentiment Momentum Score (Sₜ)
   Step 4 — Feature Engineering: Rolling averages, lagged sentiment markers
   Step 5 — Topic Modeling: LDA-style cluster analysis on sentiment themes
   Step 6 — Visualization: Platform comparison, event detection, trends

CITATIONS:
   [1] Prosus AI / FinBERT — https://huggingface.co/ProsusAI/finbert
       Pre-trained financial sentiment transformer (production implementation)
   [2] Reddit API / PRAW — https://praw.readthedocs.io
       r/streaming, r/cordcutters, r/Netflix — public sentiment source
   [3] NewsAPI — https://newsapi.org
       Streaming industry headline aggregation
   [4] Counterpoint Research Streaming Consumer Survey 2025
       Platform satisfaction and churn driver benchmarks
=============================================================================
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation, NMF
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings("ignore")

# ── Disclaimer header printed on every run ────────────────────────────────────
print("=" * 70)
print("  TV STREAMING SENTIMENT NLP ENGINE")
print("  ⚠️  ACADEMIC RESEARCH & PORTFOLIO USE ONLY")
print("  Not financial advice. No liability for investment decisions.")
print("=" * 70 + "\n")

# ── Load data ─────────────────────────────────────────────────────────────────
df = pd.read_csv("data/streaming_sentiment_raw.csv", parse_dates=['date'])
print(f"✅ Loaded: {len(df):,} daily records | "
      f"{df['platform'].nunique()} platforms | "
      f"{df['date'].min().date()} → {df['date'].max().date()}\n")

# =============================================================================
# MODULE 1 — NET SENTIMENT MOMENTUM SCORE (Sₜ) ANALYSIS
# Formula: Sₜ = (Count_Positive - Count_Negative) / (Count_Pos + Count_Neg + 1)
# =============================================================================
print("-" * 70)
print("  MODULE 1: NET SENTIMENT MOMENTUM SCORE (Sₜ) BY PLATFORM")
print("  Sₜ = (Positive - Negative) / (Positive + Negative + 1)")
print("-" * 70)

sentiment_summary = (df.groupby('platform')
                       .agg(
                           Avg_Sentiment   =('sentiment_score',        'mean'),
                           Avg_Smt         =('net_sentiment_momentum',  'mean'),
                           Peak_Positive   =('sentiment_score',        'max'),
                           Peak_Negative   =('sentiment_score',        'min'),
                           Avg_Headlines   =('n_headlines',            'mean'),
                           Total_Headlines =('n_headlines',            'sum'),
                           Positive_Days   =('sentiment_score',        lambda x: (x>0.3).sum()),
                           Negative_Days   =('sentiment_score',        lambda x: (x<0).sum()),
                       ).round(4))

print(f"\n  {'Platform':<16} {'Avg Sent':>9} {'Avg Sₜ':>8} "
      f"{'Peak+':>7} {'Peak-':>7} {'Pos Days':>10} {'Neg Days':>10}")
print("  " + "-" * 68)
for platform, row in sentiment_summary.iterrows():
    print(f"  {platform:<16} {row['Avg_Sentiment']:>9.4f} "
          f"{row['Avg_Smt']:>8.4f} "
          f"{row['Peak_Positive']:>7.4f} "
          f"{row['Peak_Negative']:>7.4f} "
          f"{int(row['Positive_Days']):>10,} "
          f"{int(row['Negative_Days']):>10,}")

sentiment_summary.to_csv('outputs/sentiment_summary.csv')

# =============================================================================
# MODULE 2 — EVENT DETECTION: MAJOR SENTIMENT SHOCKS
# =============================================================================
print("\n" + "-" * 70)
print("  MODULE 2: MAJOR SENTIMENT SHOCK EVENTS DETECTED")
print("-" * 70)

events_detected = df[df['event_note'].notna() & (df['event_note'] != '') & (df['event_note'] != 'nan')].copy()
events_detected = events_detected.sort_values('date')

print(f"\n  {len(events_detected)} shock events detected across all platforms:\n")
print(f"  {'Date':<12} {'Platform':<16} {'Sentiment':>10} {'Sₜ Score':>9}  Event")
print("  " + "-" * 70)
for _, row in events_detected.iterrows():
    direction = "🔴" if row['sentiment_score'] < 0 else "🟢"
    print(f"  {str(row['date'].date()):<12} {row['platform']:<16} "
          f"{row['sentiment_score']:>10.4f} "
          f"{row['net_sentiment_momentum']:>9.4f}  "
          f"{direction} {row['event_note']}")

events_detected.to_csv('outputs/sentiment_shock_events.csv', index=False)

# =============================================================================
# MODULE 3 — ROLLING SENTIMENT TRENDS (Feature Engineering)
# =============================================================================
print("\n" + "-" * 70)
print("  MODULE 3: ROLLING SENTIMENT FEATURES (Lagged Sₜ Indicators)")
print("-" * 70)

df = df.sort_values(['platform','date'])
for lag in [1, 3, 7, 14, 30]:
    df[f'smt_lag_{lag}d'] = df.groupby('platform')['net_sentiment_momentum'].shift(lag)

df['smt_7d_rolling_avg']  = (df.groupby('platform')['net_sentiment_momentum']
                               .transform(lambda x: x.rolling(7,  min_periods=1).mean()))
df['smt_30d_rolling_avg'] = (df.groupby('platform')['net_sentiment_momentum']
                               .transform(lambda x: x.rolling(30, min_periods=1).mean()))
df['smt_momentum_change'] = df['smt_7d_rolling_avg'] - df['smt_30d_rolling_avg']

# Sentiment regime classification
df['sentiment_regime'] = pd.cut(
    df['net_sentiment_momentum'],
    bins=[-1, -0.2, 0.0, 0.2, 0.5, 1.0],
    labels=['Strongly Bearish','Bearish','Neutral','Bullish','Strongly Bullish']
)

regime_dist = df.groupby(['platform','sentiment_regime']).size().unstack(fill_value=0)
print("\n  Sentiment Regime Distribution (trading days):\n")
print(f"  {'Platform':<16}", end='')
for col in regime_dist.columns:
    print(f"  {str(col)[:12]:>13}", end='')
print()
print("  " + "-" * 82)
for platform, row in regime_dist.iterrows():
    print(f"  {platform:<16}", end='')
    for val in row.values:
        print(f"  {val:>13,}", end='')
    print()

# =============================================================================
# MODULE 4 — TF-IDF TOPIC MODELING (Simulated Headlines)
# =============================================================================
print("\n" + "-" * 70)
print("  MODULE 4: TF-IDF TOPIC MODELING — WHAT DRIVES STREAMING SENTIMENT?")
print("-" * 70)

# Simulate realistic headline corpus based on sentiment regimes
topic_themes = {
    'positive': [
        "subscribers growth record quarterly earnings beat revenue",
        "original content hit show popular viewership milestone award",
        "international expansion new market launch partnership deal",
        "ad tier monetization pricing bundle family plan upgrade",
        "live sports rights acquisition broadcast streaming exclusive",
    ],
    'negative': [
        "subscriber loss churn cancellation password sharing crackdown",
        "price increase hike consumer backlash affordability complaint",
        "layoffs restructuring cost cutting budget reduction studio",
        "content cancellation show cancelled debt burden loss quarterly",
        "competition market share decline streaming fatigue cord cutting",
    ],
    'neutral': [
        "quarterly earnings report financial results analyst forecast",
        "content release schedule new series film documentary premiere",
        "technology infrastructure streaming quality CDN performance",
        "partnership licensing agreement content library catalog deal",
        "market analysis industry report streaming landscape overview",
    ]
}

# Build corpus
corpus = []
labels = []
for regime, headlines in topic_themes.items():
    for h in headlines:
        for _ in range(20):
            words = h.split()
            np.random.shuffle(words)
            corpus.append(' '.join(words[:np.random.randint(5, len(words)+1)]))
            labels.append(regime)

# TF-IDF vectorization
tfidf = TfidfVectorizer(max_features=200, ngram_range=(1,2),
                        stop_words='english', min_df=2)
X_tfidf = tfidf.fit_transform(corpus)

# LDA Topic Modeling
n_topics = 5
lda = LatentDirichletAllocation(n_components=n_topics, random_state=42,
                                 max_iter=30)
lda.fit(X_tfidf)

feature_names = tfidf.get_feature_names_out()
topic_names   = ['Growth & Earnings','Content Performance',
                 'Market Competition','Pricing & Churn','Tech & Infrastructure']

print(f"\n  LDA Topic Model — {n_topics} themes discovered:\n")
for i, (topic, name) in enumerate(zip(lda.components_, topic_names)):
    top_words = [feature_names[j] for j in topic.argsort()[:-8:-1]]
    print(f"  Topic {i+1} [{name}]")
    print(f"    Keywords: {' · '.join(top_words)}\n")

# Save topic model results
topic_df = pd.DataFrame(
    lda.transform(X_tfidf),
    columns=[f'Topic_{i+1}_{n}' for i, n in enumerate(topic_names)]
)
topic_df.to_csv('outputs/topic_model_distributions.csv', index=False)

# =============================================================================
# MODULE 5 — CONTENT RECOMMENDATION (TF-IDF Cosine Similarity)
# =============================================================================
print("-" * 70)
print("  MODULE 5: CONTENT SIMILARITY ENGINE (TF-IDF Cosine Similarity)")
print("-" * 70)

shows = {
    'Stranger Things':    'supernatural horror mystery teenagers 80s nostalgia adventure sci-fi',
    'The Crown':          'royal family british history drama monarchy political period',
    'Wednesday':          'dark comedy supernatural school teen mystery gothic horror',
    'Andor':              'star wars political thriller espionage rebellion empire sci-fi',
    'The Bear':           'restaurant kitchen drama chef Chicago food industry stress',
    'Severance':          'corporate dystopia mystery thriller office identity sci-fi psychological',
    'Succession':         'family dynasty corporate power media billionaire drama satire',
    'Ted Lasso':          'football soccer coach optimism British sports comedy feel-good',
    'The Last of Us':     'post-apocalyptic survival horror zombie game adaptation drama',
    'House of the Dragon':'fantasy medieval dragons political power game of thrones prequel',
    'Only Murders':       'true crime comedy podcast mystery New York apartment building',
    'Euphoria':           'teen drama drugs addiction high school relationships identity crisis',
}

show_df  = pd.DataFrame({'show': list(shows.keys()), 'description': list(shows.values())})
sv       = TfidfVectorizer(ngram_range=(1,2), stop_words='english')
show_vec = sv.fit_transform(show_df['description'])
sim_mat  = cosine_similarity(show_vec)

print("\n  Top 3 recommendations for each show:\n")
for i, show in enumerate(show_df['show']):
    sims  = list(enumerate(sim_mat[i]))
    sims  = sorted(sims, key=lambda x: x[1], reverse=True)
    recs  = [show_df['show'].iloc[j] for j, s in sims if j != i][:3]
    print(f"  If you liked '{show}':")
    for rec in recs:
        print(f"    → {rec}")
    print()

show_df.to_csv('outputs/show_similarity.csv', index=False)
pd.DataFrame(sim_mat, index=show_df['show'],
             columns=show_df['show']).to_csv('outputs/cosine_similarity_matrix.csv')

# Save enriched dataset
df.to_csv('outputs/sentiment_processed.csv', index=False)
print("\n✅ NLP Pipeline complete. Run 02_visualizations.py to generate charts.\n")
